---
apiVersion: v1
kind: Pod
metadata:
  name: app1-pod
  labels:
    app: app1
spec:
  containers:
    - name: app1-container
      image: mohfathy/app1:V1
      ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: app2-pod
  labels:
    app: app2
spec:
  containers:
    - name: app2-container
      image: mohfathy/app2:V1
      ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

