apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: ssl-certs
          mountPath: /etc/nginx/ssl
        - name: basic-auth
          mountPath: /etc/nginx/.htpasswd
          subPath: auth
        - name: html-volume
          mountPath: /usr/share/nginx/html

  initContainers:
    - name: setup-html
      image: busybox
      command:
        - sh
        - -c
        - |
          mkdir -p /usr/share/nginx/html/devops
          echo "<h1>Welcome to DevOps Dashboard</h1>" > /usr/share/nginx/html/devops/index.html
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
volumes:
    - name: html-volume
      emptyDir: {}
    - name: nginx-config
      configMap:
        name: nginx-config
    - name: ssl-certs
      secret:
        secretName: nginx-ssl
    - name: basic-auth
      secret:
        secretName: nginx-basic-auth
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
