apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: nginx
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      tty: true

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort    
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443


