apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels: 
    app: nginx  
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: ["sleep", "infinity"]
      tty: true

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort    # You can use ClusterIP if you want internal-only
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # Optional: choose your external port (range 30000–32767)

